### ISSUE TITLE
Android App crashes when trying to download an audiobook

### ISSUE THREAD

**Issue by TheLux83** [advplyr/audiobookshelf-app#144]
### Steps to reproduce

1. Define a folder
2. Try to download an audiobook

### Expected behaviour
- Downloading of the audio book

### Actual behaviour
- Either the app crashes (Tried with two folders which were named audiobookshelf and test) or it just hangs at "Downloading!" (When using an already existing audiobooks folder) and after a given time android throws an error, that it couldn't download cover.jpeg and audiobookname.m4a

### Environment data

Audiobookshelf Version: 2.0.2

- [X] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 0.9.41-beta

Device model: Google Pixel 3

Stock or customized system: Stock

#### iOS Issue
iOS Version:

iPhone model:

Hey there,

to add a few things to the details above:
- I'm using the docker image with the following docker-compose code
```
  audiobookshelf:
    container_name: audiobookshelf
    image: advplyr/audiobookshelf
    ports:
      - 13378:80
    volumes:
      - /media/data/shary/Audiobooks:/audiobooks
      - audiobookshelf_metadata:/metadata
      - audiobookshelf_config:/config
    environment:
      - AUDIOBOOKSHELF_UID=1000
      - AUDIOBOOKSHELF_GID=1000
```
The docker volumes were defined, too and the permissions should be correct.
I didn't set "Store covers with item" and "Store metadata with item" in the settings, but I also tested it with both setting options set.

Another maybe interesting fact is, that the android app isn't able to show author images even though the web app is able to.
The docker logs don't show anything interesting when the app crashes or fails to download
```
audiobookshelf        | [2022-04-24T20:01:16.330Z]  INFO: [Server] Socket eaAZY5nXzA1kfqh0AAAF disconnected from client "sascham" after 210915ms
audiobookshelf        | [2022-04-24T20:01:21.378Z]  INFO: [Server] Socket Connected CxADweT8doZw8M1KAAAH
audiobookshelf        | [2022-04-24T20:01:34.496Z]  INFO: [Server] Socket CxADweT8doZw8M1KAAAH disconnected from client "sascham" after 13118ms
audiobookshelf        | [2022-04-24T20:01:43.482Z]  INFO: [Server] Socket Connected XKDwNDbZSkwEI1bfAAAJ
audiobookshelf        | [2022-04-24T20:02:11.278Z]  INFO: [Server] Socket XKDwNDbZSkwEI1bfAAAJ disconnected from client "sascham" after 27796ms
```

I'm able to stream an audiobook in the web app and in the android app without any problems.

I think it may be a permission issue, but I cannot point with the finger at it. I even set 777 to the audiobook folder to test it, but that didn't help.

Can someone help me here?

**Comment by TheLux83** [comment]
A little Update.
I've created a podacst library, added two podcasts and tried to download them in the android app into my newly created "Podcasts" folder. 
It's the same issue. The app crashes if I try to download an episode. I can stream it without any problems.

**Comment by MidnightSnowleopard** [comment]
This has been address in the 0.9.42-beta version.  It is likely taking a bit to work through on the google play store but can be downloaded from the release section here. #128

**Comment by TheLux83** [comment]
Hey @MidnightSnowleopard, thanks for the answer.
The update is available at the play store and I downloaded it. I can confirm that the app downloads my audiobooks now.
But I have another issue now. I am able to download the audiobook, but I get an error when it was finished that says: "Item download complete but failed to create library item". It also isn't able to download the cover.jpg and I get an error on the docker logs
```
audiobookshelf        | [2022-04-25T05:40:21.718Z] ERROR: Api called without a token /items/li_z1ne06z2kgk6uon320/cover
```

I've tested podcasts and it seems that I can download them. Even though I get an error message there too and it doesn't show the cover art on the local shelf
```
audiobookshelf        | TypeError: li.media.metadata.hasSeries is not a function
audiobookshelf        |     at /server/utils/libraryHelpers.js:25:83
audiobookshelf        |     at Array.filter (<anonymous>)
audiobookshelf        |     at Object.getFilteredLibraryItems (/server/utils/libraryHelpers.js:25:31)
audiobookshelf        |     at ApiRouter.getLibraryItems (/server/controllers/LibraryController.js:161:37)
audiobookshelf        |     at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
audiobookshelf        |     at next (/node_modules/express/lib/router/route.js:137:13)
audiobookshelf        |     at ApiRouter.middleware (/server/controllers/LibraryController.js:594:5)
audiobookshelf        |     at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
audiobookshelf        |     at next (/node_modules/express/lib/router/route.js:137:13)
audiobookshelf        |     at Route.dispatch (/node_modules/express/lib/router/route.js:112:3)
audiobookshelf        | [2022-04-25T05:48:31.181Z] ERROR: Api called without a token /items/li_qy959eh20d4g0evz45/cover
```

**Comment by advplyr** [comment]
Getting there, thanks for the logs. These should be easy ones.

**Comment by advplyr** [comment]
Fixed the cover issue will be in the next release. The second issue was unrelated and had to do with podcast filtering, that will be in the next server release.

**Comment by Strider27** [comment]
The app still crashes when scanning local folders but only with some books (looks like .m4b specific so far, with many chapters)
Looking at the log it looks like FFprobe fails partways through chapter 23, the book has 41 chapters.

Still issue with Covers for local books as well, not sure if [31c753f](https://github.com/advplyr/audiobookshelf-app/commit/31c753ffccb2c62c64aba745c16fb2e2d779f00d) has made it to Unraid Docker yet, just making a note, just in case.

App: 0.9.42-beta
Server: V2.0.3
Running in Unraid Docker

Logcat below, not sure how much of it you need so just grabbed a good bit.


<details>
  <summary>Logcat Contents</summary>

<pre>
AbsFileSystem: Scan Folder cHJpbWFyeTpBdWRpb2Jvb2tz
04-27 00:36:36.917 24184 24372 D AbsFileSystem:  | Force Audio Probe false
04-27 00:36:36.919 24184 24372 I ffmpeg-kit: Loading ffmpeg-kit.
04-27 00:36:36.922 24184 24184 I IMM_LC  : hsifw() - flags=0, caller=android.view.inputmethod.InputMethodManager.hideSoftInputFromWindow:1846 org.chromium.content.browser.input.ImeAdapterImpl.f:174 org.chromium.content.browser.input.ImeAdapterImpl.updateState:525 android.os.MessageQueue.nativePollOnce:-2 android.os.MessageQueue.next:335
04-27 00:36:36.922 24184 24184 I IMM_LC  : hideSoftInputFromWindow - mService.hideSoftInput
04-27 00:36:36.923   946  1827 D InputMethodManagerService: hideSoftInput
04-27 00:36:36.923   946  1827 V InputMethodManagerService: Client requesting input be hidden
04-27 00:36:36.923   946  1827 V InputMethodManagerService: hideCurrentInputLocked : shouldHideSoftInput is false
04-27 00:36:36.927 24184 24372 I ffmpeg-kit: Loaded ffmpeg-kit-min-arm64-v8a-4.5.1-20211230.
04-27 00:36:36.928 24184 24667 D ffmpeg-kit: Async callback block started.
04-27 00:36:36.965 24184 24372 D FolderScanner: scanForMediaItems Checking Existing LLI local_cHJpbWFyeTpBdWRpb2Jvb2tzL1N0YXJzaGlwIExpYmVyYXRvcg==
04-27 00:36:36.965 24184 24372 D FolderScanner: scanForMediaItems Checking Existing LLI local_cHJpbWFyeTpBdWRpb2Jvb2tzL0JhdHRsZXNoaXAgSW5kb21pdGFibGU=
04-27 00:36:36.965 24184 24372 D FolderScanner: scanForMediaItems Checking Existing LLI local_cHJpbWFyeTpBdWRpb2Jvb2tzL0hpdmUgd2Fy
04-27 00:36:36.967 24184 24372 D FolderScanner: Iterating over Folder Found Flagship Victory | primary:Audiobooks/Flagship Victory | URI: content://com.android.externalstorage.documents/tree/primary%3AAudiobooks/document/primary%3AAudiobooks%2FFlagship%20Victory
04-27 00:36:36.983 24184 24372 D FolderScanner: Found audio/mp4 file 03-Flagship Victory.m4b in folder Flagship Victory
04-27 00:36:36.986 24184 24372 D FolderScanner: File attributes Id:cHJpbWFyeTpBdWRpb2Jvb2tzL0ZsYWdzaGlwIFZpY3RvcnkvMDMtRmxhZ3NoaXAgVmljdG9yeS5tNGI=|ContentUrl:content://com.android.externalstorage.documents/tree/primary%3AAudiobooks/document/primary%3AAudiobooks%2FFlagship%20Victory%2F03-Flagship%20Victory.m4b|isDownloadsDocument:false
04-27 00:36:36.986 24184 24372 D FolderScanner: scanLibraryItemFolder Scanning Audio File Path /storage/emulated/0/Audiobooks/Flagship Victory/03-Flagship Victory.m4b | ForceAudioProbe=false
04-27 00:36:37.029   457   457 D io_stats: !@   8,0 r 20913524 632028736 w 17319529 432122040 d 0 0 f 0 0 iot 11237276 0 th 0 0 0 pt 0 inp 0 0 767456.874
04-27 00:36:37.195 24184 24372 D FolderScanner: FFprobe output {"streams":[{"index":0,"codec_name":"aac","codec_long_name":"unknown","profile":"1","codec_type":"audio","codec_tag_string":"mp4a","codec_tag":"0x6134706d","sample_fmt":"fltp","sample_rate":"22050","channels":2,"channel_layout":"stereo","bits_per_sample":0,"id":"0x1","r_frame_rate":"0\/0","avg_frame_rate":"0\/0","time_base":"1\/22050","start_pts":0,"start_time":"0.000000","duration_ts":1296758784,"duration":"58809.922177","bit_rate":"62794","nb_frames":"1266366","disposition":{"default":1,"dub":0,"original":0,"comment":0,"lyrics":0,"karaoke":0,"forced":0,"hearing_impaired":0,"visual_impaired":0,"clean_effects":0,"attached_pic":0,"timed_thumbnails":0,"captions":0,"descriptions":0,"metadata":0,"dependent":0,"still_image":0},"tags":{"language":"und","handler_name":"SoundHandler","vendor_id":"[0][0][0][0]"}}],"chapters":[{"id":0,"time_base":"1\/1000","start":0,"start_time":"0.000000","end":1916714,"end_time":"1916.714000","tags":{"title":"001"}},{"id":1,"time_base":"1\/1000","start":1916714,"start_time":"1916.714000","end":3190468,"end_time":"3190.468000","tags":{"title":"002"}},{"id":2,"time_base":"1\/1000","start":3190468,"start_time":"3190.468000","end":4705430,"end_time":"4705.430000","tags":{"title":"003"}},{"id":3,"time_base":"1\/1000","start":4705430,"start_time":"4705.430000","end":6086182,"end_time":"6086.182000","tags":{"title":"004"}},{"id":4,"time_base":"1\/1000","start":6086182,"start_time":"6086.182000","end":7432893,"end_time":"7432.893000","tags":{"title":"005"}},{"id":5,"time_base":"1\/1000","start":7432893,"start_time":"7432.893000","end":8947484,"end_time":"8947.484000","tags":{"title":"006"}},{"id":6,"time_base":"1\/1000","start":8947484,"start_time":"8947.484000","end":10042165,"end_time":"10042.165000","tags":{"title":"007"}},{"id":7,"time_base":"1\/1000","start":10042165,"start_time":"10042.165000","end":11892517,"end_time":"11892.517000","tags":{"title":"008"}},{"id":8,"time_base":"1\/1000","start":11892517,"start_time":"11892.517000","end":12977725,"end_time":"12977.725000","tags":{"title":"009"}},{"id":9,"time_base":"1\/1000","start":12977725,"start_time":"12977.725000","end":14203832,"end_time":"14203.832000","tags":{"title":"010"}},{"id":10,"time_base":"1\/1000","start":14203832,"start_time":"14203.832000","end":15779538,"end_time":"15779.538000","tags":{"title":"011"}},{"id":11,"time_base":"1\/1000","start":15779538,"start_time":"15779.538000","end":16854529,"end_time":"16854.529000","tags":{"title":"012"}},{"id":12,"time_base":"1\/1000","start":16854529,"start_time":"16854.529000","end":18143468,"end_time":"18143.468000","tags":{"title":"013"}},{"id":13,"time_base":"1\/1000","start":18143468,"start_time":"18143.468000","end":19820413,"end_time":"19820.413000","tags":{"title":"014"}},{"id":14,"time_base":"1\/1000","start":19820413,"start_time":"19820.413000","end":21087759,"end_time":"21087.759000","tags":{"title":"015"}},{"id":15,"time_base":"1\/1000","start":21087759,"start_time":"21087.759000","end":22481931,"end_time":"22481.931000","tags":{"title":"016"}},{"id":16,"time_base":"1\/1000","start":22481931,"start_time":"22481.931000","end":23821397,"end_time":"23821.397000","tags":{"title":"017"}},{"id":17,"time_base":"1\/1000","start":23821397,"start_time":"23821.397000","end":25443218,"end_time":"25443.218000","tags":{"title":"018"}},{"id":18,"time_base":"1\/1000","start":25443218,"start_time":"25443.218000","end":26602405,"end_time":"26602.405000","tags":{"title":"019"}},{"id":19,"time_base":"1\/1000","start":26602405,"start_time":"26602.405000","end":28016314,"end_time":"28016.314000","tags":{"title":"020"}},{"id":20,"time_base":"1\/1000","start":28016314,"start_time":"28016.314000","end":30035893,"end_time":"30035.893000","tags":{"title":"021"}},{"id":21,"time_base":"1\/1000","start":30035893,"start_time":"30035.893000","end":31508271,"end_time":"31508.271000","tags":{"title":"022"}},{"id":22,"time_base":"1\/1000","start":31508271,"start_time":"31508.271000","end":32884703,"end_time":"32884.703000","tags":{"title":"023"}},{"id":23,"
04-27 00:36:37.211 24184 24372 E AndroidRuntime: FATAL EXCEPTION: CapacitorPlugins
04-27 00:36:37.211 24184 24372 E AndroidRuntime: Process: com.audiobookshelf.app, PID: 24184
04-27 00:36:37.211 24184 24372 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:601)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:226)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:313)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:67)
04-27 00:36:37.211 24184 24372 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:592)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        ... 6 more
04-27 00:36:37.211 24184 24372 E AndroidRuntime: Caused by: com.fasterxml.jackson.databind.JsonMappingException: Numeric value (574527620000) out of range of int (-2147483648 - 2147483647)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:  at [Source: (String)"{
04-27 00:36:37.211 24184 24372 E AndroidRuntime:     "streams": [
04-27 00:36:37.211 24184 24372 E AndroidRuntime:         {
04-27 00:36:37.211 24184 24372 E AndroidRuntime:             "index": 0,
04-27 00:36:37.211 24184 24372 E AndroidRuntime:             "codec_name": "aac",
04-27 00:36:37.211 24184 24372 E AndroidRuntime:             "codec_long_name": "unknown",
04-27 00:36:37.211 24184 24372 E AndroidRuntime:             "profile": "1",
04-27 00:36:37.211 24184 24372 E AndroidRuntime:             "codec_type": "audio",
04-27 00:36:37.211 24184 24372 E AndroidRuntime:             "codec_tag_string": "mp4a",
04-27 00:36:37.211 24184 24372 E AndroidRuntime:             "codec_tag": "0x6134706d",
04-27 00:36:37.211 24184 24372 E AndroidRuntime:             "sample_fmt": "fltp",
04-27 00:36:37.211 24184 24372 E AndroidRuntime:             "sample_rate": "22050",
04-27 00:36:37.211 24184 24372 E AndroidRuntime:             "channels": 2,
04-27 00:36:37.211 24184 24372 E AndroidRuntime:             "channel_layout": "stereo",
04-27 00:36:37.211 24184 24372 E AndroidRuntime:             "bits_per_sample": 0,
04-27 00:36:37.211 24184 24372 E AndroidRuntime:             "id": "0x1",
04-27 00:36:37.211 24184 24372 E AndroidRuntime:             "r_frame_rate": "0/0","[truncated 14211 chars]; line: 496, column: 34] (through reference chain: com.audiobookshelf.app.data.AudioProbeResult["chapters"]->java.util.ArrayList[40]->com.audiobookshelf.app.data.AudioProbeChapter["start"])
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1807)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:567)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:449)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1390)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:362)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:347)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:565)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:449)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1390)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:362)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3548)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3531)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at com.audiobookshelf.app.device.FolderScanner.probeAudioFile(FolderScanner.kt:472)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at com.audiobookshelf.app.device.FolderScanner.scanLibraryItemFolder(FolderScanner.kt:153)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at com.audiobookshelf.app.device.FolderScanner.scanForMediaItems(FolderScanner.kt:73)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at com.audiobookshelf.app.plugins.AbsFileSystem.scanFolder(AbsFileSystem.kt:148)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        ... 9 more
04-27 00:36:37.211 24184 24372 E AndroidRuntime: Caused by: com.fasterxml.jackson.core.exc.InputCoercionException: Numeric value (574527620000) out of range of int (-2147483648 - 2147483647)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:  at [Source: (String)"{
04-27 00:36:37.211 24184 24372 E AndroidRuntime:     "streams": [
04-27 00:36:37.211 24184 24372 E AndroidRuntime:         {
04-27 00:36:37.211 24184 24372 E AndroidRuntime:             "index": 0,
04-27 00:36:37.211 24184 24372 E AndroidRuntime:             "codec_name": "aac",
04-27 00:36:37.211 24184 24372 E AndroidRuntime:             "codec_long_name": "unknown",
04-27 00:36:37.211 24184 24372 E AndroidRuntime:             "profile": "1",
04-27 00:36:37.211 24184 24372 E AndroidRuntime:             "codec_type": "audio",
04-27 00:36:37.211 24184 24372 E AndroidRuntime:             "codec_tag_string": "mp4a",
04-27 00:36:37.211 24184 24372 E AndroidRuntime:             "codec_tag": "0x6134706d",
04-27 00:36:37.211 24184 24372 E AndroidRuntime:             "sample_fmt": "fltp",
04-27 00:36:37.211 24184 24372 E AndroidRuntime:             "sample_rate": "22050",
04-27 00:36:37.211 24184 24372 E AndroidRuntime:             "channels": 2,
04-27 00:36:37.211 24184 24372 E AndroidRuntime:             "channel_layout": "stereo",
04-27 00:36:37.211 24184 24372 E AndroidRuntime:             "bits_per_sample": 0,
04-27 00:36:37.211 24184 24372 E AndroidRuntime:             "id": "0x1",
04-27 00:36:37.211 24184 24372 E AndroidRuntime:             "r_frame_rate": "0/0","[truncated 14211 chars]; line: 496, column: 34]
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportInputCoercion(ParserMinimalBase.java:599)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at com.fasterxml.jackson.core.base.ParserMinimalBase.reportOverflowInt(ParserMinimalBase.java:568)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at com.fasterxml.jackson.core.base.ParserBase.convertNumberToInt(ParserBase.java:936)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at com.fasterxml.jackson.core.base.ParserBase._parseIntValue(ParserBase.java:849)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at com.fasterxml.jackson.core.base.ParserBase.getIntValue(ParserBase.java:680)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:526)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:506)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:565)
04-27 00:36:37.211 24184 24372 E AndroidRuntime:        ... 30 more
04-27 00:36:37.215   946 24668 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
04-27 00:36:37.216   946  1530 D Debug   : low && ship && 3rdparty app crash, do not dump
04-27 00:36:37.216   946  1530 W ActivityManager: crash : com.audiobookshelf.app,11123
04-27 00:36:37.216   946  1530 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1242 com.android.server.am.AppErrors.crashApplicationInner:723 com.android.server.am.AppErrors.crashApplication:584 com.android.server.am.ActivityManagerService.handleApplicationCrashInner:9723 com.android.server.am.ActivityManagerService.handleApplicationCrash:9602
04-27 00:36:37.217   946  1530 W ActivityTaskManager:   Force finishing activity com.audiobookshelf.app/.MainActivity
04-27 00:36:37.217   946  1530 W WindowManager: Prepare app transition: mNextAppTransitionRequests=[TRANSIT_CLOSE], mNextAppTransitionFlags=TRANSIT_FLAG_APP_CRASHED, displayId: 0 Callers=com.android.server.wm.DisplayContent.prepareAppTransition:6358 com.android.server.wm.Task.finishTopCrashedActivityLocked:8838 com.android.server.wm.RootWindowContainer.lambda$finishTopCrashedActivities$20:2775 com.android.server.wm.RootWindowContainer$$ExternalSyntheticLambda30.accept:10 com.android.server.wm.Task.forAllTasks:5158
04-27 00:36:37.217   946  1530 W WindowManager: Prepare app transition: mNextAppTransitionRequests=[TRANSIT_CLOSE, TRANSIT_CLOSE], mNextAppTransitionFlags=TRANSIT_FLAG_APP_CRASHED, displayId: 0 Callers=com.android.server.wm.DisplayContent.prepareAppTransition:6358 com.android.server.wm.DisplayContent.requestTransitionAndLegacyPrepare:6373 com.android.server.wm.Task.finishTopCrashedActivityLocked:8839 com.android.server.wm.RootWindowContainer.lambda$finishTopCrashedActivities$20:2775 com.android.server.wm.RootWindowContainer$$ExternalSyntheticLambda30.accept:10
04-27 00:36:37.218   946  1530 D InputDispatcher: Focused application set to (0): 4396521
04-27 00:36:37.218   946  1530 V WindowManager: Changing focus from Window{9b3325c u0 com.audiobookshelf.app/com.audiobookshelf.app.MainActivity} to null displayId=0 Callers=com.android.server.wm.RootWindowContainer.updateFocusedWindowLocked:583 com.android.server.wm.WindowManagerService.updateFocusedWindowLocked:6461 com.android.server.wm.ActivityTaskManagerService.setResumedActivityUncheckLocked:5470 com.android.server.wm.ActivityRecord.moveFocusableActivityToTop:3333
04-27 00:36:37.218   946  1530 D MARsPolicyManager: onPackageResumedFG pkgName = com.audiobookshelf.app, userId = 0
04-27 00:36:37.218   946  1530 D StatusBarManagerService: notifyRequestedSystemKey recent=false home=false
04-27 00:36:37.218   946  1530 D SGM:GameManager: TaskStackListener.onTaskFocusChanged(), taskId=1533, focused=false
04-27 00:36:37.218   946  1530 D SGM:GameManager: TaskStackListener.onTaskFocusChanged(), taskId=591, focused=true
04-27 00:36:37.218   946  1530 D SGM:GameManager:   sendRunningComponentFocus(), pkgName: com.sec.android.app.launcher, userId: 0
04-27 00:36:37.218   946  1165 D SGM:GameManager: onLooperPrepared(), msg: MSG_TASK_FOCUSED, pkgName: com.sec.android.app.launcher, userId: 0
04-27 00:36:37.218   946  1165 D SGM:GameManager: handleTaskFocused().
04-27 00:36:37.219   946  1165 D SGM:GameManager: sendFocusOutConditionally() - mPrevNotiPkg: KILL_YOURSELF, userId: 0
04-27 00:36:37.219   946  1165 D SGM:GameManager:   handleTaskFocused(), pkgName: com.sec.android.app.launcher, userID:0 mResumedPkgMap does not containsKey.
04-27 00:36:37.219   946  1530 W WindowManager: Prepare app transition: mNextAppTransitionRequests=[TRANSIT_CLOSE, TRANSIT_CLOSE, TRANSIT_CLOSE], mNextAppTransitionFlags=TRANSIT_FLAG_APP_CRASHED, displayId: 0 Callers=com.android.server.wm.DisplayContent.prepareAppTransition:6358 com.android.server.wm.DisplayContent.prepareAppTransition:6353 com.android.server.wm.ActivityRecord.finishIfPossible:3619 com.android.server.wm.ActivityRecord.finishIfPossible:3425 com.android.server.wm.Task.finishTopCrashedActivityLocked:8840
04-27 00:36:37.219   946  1530 D RestrictionPolicy: isScreenCaptureEnabled : ret=true userId=0
04-27 00:36:37.219   946  1530 D RestrictionPolicy: isScreenCaptureEnabled : ret=true userId=0
04-27 00:36:37.234   627   627 I Layer   : id=114758 Destroyed Screenshot Parent
04-27 00:36:37.249   530   537 E statsd  : Predicate -7037417284711607308 dropping data for dimension key (10)0x2010101->11123[I] (10)0x30000->*launch*[S]
04-27 00:36:37.254  1352  1369 E TaskStackListenerAbstract: onTaskSnapshotChanged called by Binder.getCallingPid() 0 android.app.ITaskStackListener$Stub.onTransact:585 android.os.Binder.execTransactInternal:1220 android.os.Binder.execTransact:1179 <bottom of call stack>
04-27 00:36:37.255  3564 14321 E TaskStackListenerAbstract: onTaskSnapshotChanged called by Binder.getCallingPid() 0 android.app.ITaskStackListener$Stub.onTransact:585 android.os.Binder.execTransactInternal:1220 android.os.Binder.execTransact:1179 <bottom of call stack>
04-27 00:36:37.255  4218  4294 E TaskStackListenerAbstract: onTaskSnapshotChanged called by Binder.getCallingPid() 0 android.app.ITaskStackListener$Stub.onTransact:585 android.os.Binder.execTransactInternal:1220 android.os.Binder.execTransact:1179 <bottom of call stack>
04-27 00:36:37.255   946  1827 V MARsPolicyManager: Current Home Package com.sec.android.app.launcher Resumed
04-27 00:36:37.255   946  1827 I SemDvfsHyPerManager: acquire hyper - AMS_APP_HOME/946@35, type = -999
04-27 00:36:37.256   570   618 I HYPER-HAL: [RequestManager.cpp]acquire(): Acquired ID : 481706  [946 / 35]    HINT : AMS_APP_HOME    list :
04-27 00:36:37.256  1352  1985 E TaskStackListenerAbstract: onTaskSnapshotChanged called by Binder.getCallingPid() 0 android.app.ITaskStackListener$Stub.onTransact:585 android.os.Binder.execTransactInternal:1220 android.os.Binder.execTransact:1179 <bottom of call stack>
04-27 00:36:37.257   946  1827 D ActivityManagerPerformance: AMP_acquire() HOME
04-27 00:36:37.258   530   537 E statsd  : Predicate -7037417284711607308 dropping data for dimension key (10)0x2010101->11123[I] (10)0x30000->*launch*[S]
04-27 00:36:37.258   946  1827 W WindowManager: Prepare app transition: mNextAppTransitionRequests=[TRANSIT_CLOSE, TRANSIT_CLOSE, TRANSIT_CLOSE, TRANSIT_CLOSE], mNextAppTransitionFlags=TRANSIT_FLAG_APP_CRASHED, displayId: 0 Callers=com.android.server.wm.DisplayContent.prepareAppTransition:6358 com.android.server.wm.DisplayContent.prepareAppTransition:6353 com.android.server.wm.Task.resumeTopActivityInnerLocked:8369 com.android.server.wm.Task.resumeTopActivityInnerLocked:8098 com.android.server.wm.Task.resumeTopActivityUncheckedLocked:7996
</pre>

</details>

**Comment by Strider27** [comment]
Just realised that the crashes have probably been resolved in [52fd8ac](https://github.com/advplyr/audiobookshelf-app/commit/52fd8ac5e827f28016c9f7dca1b01bca6738335d) by changing int to Long for the timestamps. If so, can we get an apk build, pretty please 😃?  It is driving me crazy as most series have some books working and some not and I can't finish any series 😞

**Comment by Strider27** [comment]
@TheLux83 
That's already fixed in 0.9.43-beta, the APK is in the releases section if you don't want to waith for Google Play Store update,

**Comment by advplyr** [comment]
[v0.9.43-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.43-beta) is live with the fix.
