### ISSUE TITLE
(Android) Stop button on notification player

### ISSUE THREAD

**Issue by skyzuma** [advplyr/audiobookshelf-app#268]
### Steps to reproduce

1. open listen book
2. play book
3. try stop button after few seconds of listening on notification player

### Expected behaviour
- stop book and save current listen time

### Actual behaviour
- marked book as finished

### Environment data

Audiobookshelf Version: 2.0.23

- [x] Android App?

#### Android Issue
Android version: 9

Device model: Huawei P10 (an my tablet SM-T725 there is no stop button on the notification player)

Stock or customized system: Stock

tested with server version: 2.0.22 / 23

**Comment by advplyr** [comment]
I wasn't able to reproduce this.

**Comment by skyzuma** [comment]
i think is misspelled ... marked book as finished  ... if i use the stop button the book is gone from the "current listen" and the progress is 0 lile a new book

**Comment by advplyr** [comment]
is this a downloaded book?

did the book already have saved progress before you started playing it?

This is not happening for me.

**Comment by skyzuma** [comment]
> is this a downloaded book?

no

> did the book already have saved progress before you started playing it?

yes

**Comment by advplyr** [comment]
are you able to reproduce this every time?

**Comment by skyzuma** [comment]
yes, ive tested 3 books:

open app > play a book > play it for 2/3 min (shown in Continue Listening section) > swipe down the notifications > press stop > book are resettet

**Comment by advplyr** [comment]
What is a "prorassion label"?

**Comment by skyzuma** [comment]
oh sry: progression label / line (the yellow line)

**Comment by advplyr** [comment]
Using the latest mobile app version 0.9.52-beta and the latest server version 2.0.24 are you still able to reproduce this issue?

**Comment by skyzuma** [comment]
(Huawei P10 / Android 9)

yes ... played a book 10 min ... the log show "syncSession" and if i tap the stop button on the notification player > no syncSession (no any other informations except ping) and the book looks like never played and its not on "continue listening" ...

(SM-T725 / Android 11 ))

there is no stop button on the notification player

**Comment by advplyr** [comment]
I thought you said when you press stop in the notification then it marks the book as finished?

**Comment by skyzuma** [comment]
marked as played was my first statement but i corrected it in my second statement ...

**Comment by advplyr** [comment]
You start streaming a book that has progress. Open up the notification and press the stop button. Then the progress is cleared on the mobile app and on the server, is that correct?

**Comment by skyzuma** [comment]
yes (if i open web, i see the book opened on the bottom but with 0 progress) ... this happens also also on books without progress ...

**Comment by skyzuma** [comment]
Same on SM-T725 with andorid 11. I heared a book for 8 hours in total the last days and today I found the stop button on the notification player (there was an arrow) and i pressed this button and the progression of the book was resetted to 0 and was also gone from the continue listening shelf.

**Comment by advplyr** [comment]
Fixed in [v0.9.53-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.53-beta)

**Comment by skyzuma** [comment]
v0.9.53-beta: not fixed for me on Huawei P10 (android 9) and SM-T725 (Android 11)

**Comment by skyzuma** [comment]
v0.9.53-beta:
Huawei P10 (android 9) fixed for one book (the first book from "recently added" / the last added book)) but on all other books the progress was removed after stop from notification player ... app was removed and reinstalled ... if one book is listened (have progress) and its listed under "continue  Listening" > the first book from "recently added" will lose the progression after stop from notification player ...

SM-T725 (Android 11) ... not fixed but there is one book in "continue  Listening" with progress (looks like same as android 9 abouve)  ... app was removed and reinstalled

**Comment by skyzuma** [comment]
look like its fixed (on both devices) with 0.9.55 ... thx ...
