### ISSUE TITLE
Wrong server version being reported

### ISSUE THREAD

**Issue by mediacowboy** [advplyr/audiobookshelf-app#295]
### Steps to reproduce

1. Update server to 2.1.0
2. Open app 
3. Deleted cached server information 
4. Log in
5. Look at server version
6. Show last server version 

### Expected behaviour
- Show correct server version

### Actual behaviour
- shows last server version you were on

### Environment data

Audiobookshelf Version:

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 12

Device model: Samsung S10+

Stock or customized system: stock 

#### iOS Issue
iOS Version:

iPhone model:

**Comment by mediacowboy** [comment]
![Screenshot_20220718-193618_audiobookshelf.jpg](https://user-images.githubusercontent.com/12468863/179640691-cdc168d1-e166-4ca9-99a8-759a1bd91d9f.jpg)

**Comment by mediacowboy** [comment]
Web Gui

![Screenshot_20220718-193611_Chrome.jpg](https://user-images.githubusercontent.com/12468863/179640749-505feedd-5f12-4602-9840-6eda62f932ed.jpg)

**Comment by duplaja** [comment]
Seeing this as well, showing version 2.0.20. I've updated to all the intermediate versions between this and 2.1.0, but may not have used the mobile app during that time.

**Comment by advplyr** [comment]
Fixed in [v0.9.53-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.53-beta)

**Comment by skyzuma** [comment]
v0.9.53-beta: not fixed:

Huawei P10: android 9 (URL (2.0.24) (app) instead of 2.1.0 (web))
SM-T725: android 11 (URL (v) (app))

**Comment by advplyr** [comment]
Unfortunately you still need to logout and log back in for it to refresh. I'll update that in a future version so it updates when the socket reconnects

**Comment by skyzuma** [comment]
"logout and log back in for it to refresh" not fixed but after reinstall the app it fixed on both devices ...
