### ISSUE TITLE
[Android] Playback speed not saving between sessions 

### ISSUE THREAD

**Issue by nathanmilot** [advplyr/audiobookshelf-app#532]
### Steps to reproduce

1. Open the app and begin playing a book
2. Change the playback speed to something other than 1.
3. Pause and close the app.
4. Reopen and play the same book.

### Expected behaviour
- Tell us what should happen
Playback should be at the selected speed. The previous version of the app did this.

### Actual behaviour
- Tell us what happens
It defaults to 1x. 

### Environment data

Audiobookshelf Version: 0.9.61-beta

- [X] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 13

Device model:Google Pixel 6 Pro

Stock or customized system: stock

#### iOS Issue
iOS Version:

iPhone model:

**Comment by mym0T** [comment]
This issue may be specific to Android. I am not able to reproduce it on iOS with version 0.9.61

**Comment by advplyr** [comment]
I did further testing on this and it specifically has to do with the first media that loads when launching the app. The problem was a race condition between loading the saved playback speed and setting the media.

This was specific to Android but there was another bug that affected both iOS/Android after updating from any version before 0.9.61. This resolves itself after selecting the playback speed again.

**Comment by jcrmit** [comment]
This behaviour is still occuring after update to v0.9.63-beta

**Comment by advplyr** [comment]
@jcrmit You sideloaded the APK?

**Comment by jcrmit** [comment]
Yes I always do. Is that an issue?

**Comment by advplyr** [comment]
Not an issue.
If you set the playback speed on an audiobook. Close and re-open the app. The most recent audiobooks should automatically open and that is not showing the updated playback speed?

**Comment by jcrmit** [comment]
Have an audioplaying set to 1.4x (intentionally changed from 1.5x)
Closed the re-opened the app
The book that was playing opens (in bottom banner)
When I click to expand, playback speed have returned to 1x

**Comment by rweatherly** [comment]
I wanted to jump in and add that both myself (Pixel 7) and a friend of mine (Pixel 6) are experiencing the same issue, we are both using the play store version, not sideloaded. its not every time, but it does occur at least once every day or three

**Comment by i-am-at0m** [comment]
I also noticed it on my Pixel 7 Pro and just gave up on using it because I open the app multiple times a day but rarely switch books.

**Comment by advplyr** [comment]
I thought I fixed this in the 0.9.63-beta just released on the play store. Can others test this on the latest version?

**Comment by i-am-at0m** [comment]
Nope, not fixed. Have a video showing how I reproduced it, but don't want to post them publicly because they have my server url in them. How can I get it to you?

**Comment by rweatherly** [comment]
SO i checked with my friend who did also get the update and she is having the issue, while it seems im not. She reported then when she fully backed out of the app and then when its started and has to connect to the server, it seems to be that time when it does the reset. I tested this and it does not happen to me. It does seem to be taking longer to connect with this update though. 
the only difference im aware of is that the ABS server is on my local network, so im connecting over the LAN, and she is going over the internet to a reverse proxy that is passing the traffic to the server. Let me know if there is any other tests, or logs that i can gather that would be useful

**Comment by advplyr** [comment]
I was just able to reproduce this so hopefully I can track it down now. It does appear to be a race condition since sometimes it happens sometimes it doesn't. Thanks for all the info

**Comment by PyroghostX** [comment]
My friend and I both have this on android on the latest google play version.

Have you been able to figure it out? Is there any troubleshooting I can help do?

**Comment by advplyr** [comment]
The problem was the auto-opening of the most recent listened item. This was removed

**Comment by advplyr** [comment]
Just tested and this issue persists

**Comment by PyroghostX** [comment]
I haven't had it, playback has stayed at 1.7x for a while now

**Comment by advplyr** [comment]
@PyroghostX On Android?

**Comment by PyroghostX** [comment]
yes, android 13

**Comment by rweatherly** [comment]
Jumping in to report two more Android 13 Pixels that have not seen any issues with the playback speed since the latest update. We are both daily users of it.

**Comment by advplyr** [comment]
Hmm that's good news but also makes this more confusing as some people are.
By any chance did you uninstall and reinstall the app completely at some point between when the bug was happening and it being fixed?

**Comment by rweatherly** [comment]
Neither of us have done an app reinstall.

**Comment by feerlessleadr** [comment]
Same position as others. I'm on Android 13 on my OnePlus 8t and I haven't had this issue since it was resolved back in April. I didn't uninstall and reinstall or anything.

**Comment by rendyhd** [comment]
The issue is fixed for me too, no new install just updated to last version

**Comment by advplyr** [comment]
I found a bug where the promise was never getting resolved resulting in the locally saved playback speed never getting fetched. This explains why it happens sometimes or for some users and not others.

**Comment by advplyr** [comment]
Fixed in [v0.9.65-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.65-beta)
