### ISSUE TITLE
Low resolution cover in the android media controls notification when streaming

### ISSUE THREAD

**Issue by nikerl** [advplyr/audiobookshelf-app#657]
### Steps to reproduce

1. Start playing any book that has to be streamed from the server
2. Pull down the notification shade and look at the media controls notification

### Expected behaviour
- The cover shown in the media controls notification should have the same quality as the one in the app.

### Actual behaviour
- The cover in the media controls notification has a much lower resolution than the source image. See attached screenshots. This issue does not appear when the book has been downloaded, only when streaming it from the server.

[cover in app](https://user-images.githubusercontent.com/44620116/229313781-9d502081-d03e-4731-846b-1c5c921147d3.png)
[cover in media controls notification](https://user-images.githubusercontent.com/44620116/229313784-56dae79c-a3c3-4814-b532-8f9da4a0ed49.png)

### Environment data

Audiobookshelf Version: server: 2.2.17, app: 0.9.63-beta

- [x] Android App? 
- [ ] iOS App?

#### Android Issue
Android version: Android 13 (TQ2A.230305.008)

Device model: Google Pixel 7

Stock or customized system: Stock

**Comment by advplyr** [comment]
I updated Glide so that it doesn't resize the image anymore. In my testing Glide was still reducing the quality of the image a lot but it is noticeably better.

**Comment by advplyr** [comment]
Fixed in [v0.9.74-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.74-beta)

**Comment by senornada** [comment]
Hi, for me, the problem still exists in the latest version 0.9.77-BETA.

**Comment by hndrk-themer** [comment]
Totally true. For me as well. 0.9.77 beta android 15 pixel 9

**Comment by psbordjukov** [comment]
Confirming issue still exists in 0.9.79 beta. @advplyr, please consider reopening.

**Comment by psbordjukov** [comment]
Sure!

![Image](https://github.com/user-attachments/assets/26b1835d-5dec-4a6d-a5bb-d7da38609912)

**Comment by psbordjukov** [comment]
I can add adb logs or server access logs if you wish, just say the word.

**Comment by psbordjukov** [comment]
(I suspect it's an issue with ExoPlayer)

**Comment by pounat** [comment]
Getting this on my Samsung s25 as well. 

In the app
![Image](https://github.com/user-attachments/assets/9809408e-b65f-4a7f-82f6-612e32eb6cb3)

On lock screen
![Image](https://github.com/user-attachments/assets/ede6ac76-77cf-4bb6-8719-945e0e9b4c55)

Media controls
![Image](https://github.com/user-attachments/assets/f905cdb5-297e-4f75-8b5e-ed5d4d297552)

**Comment by jaredtodworkman** [comment]
This was fixed for me in 0.9.81-beta but seems to be broken again in V0.10.0-beta. Using a Pixel 6a. Tell me if you'd like me to send screenshots.

**Comment by bleov** [comment]
Noticing the same issue (although seemingly less severe) on iOS 26  with 0.10.1-beta on the lock screen and media controls in the control center.

![image](https://github.com/user-attachments/assets/8184fa8f-506d-48e0-af11-32e5112c8963)
