### ISSUE TITLE
Progress lost on downloaded audiobooks when connected to server

### ISSUE THREAD

**Issue by wbio** [advplyr/audiobookshelf-app#828]
### Steps to reproduce

1. Listen to locally-downloaded audiobook
2. Close app
3. Reopen app

### Expected behaviour
- Progress is kept at current position

### Actual behaviour
- Progress is reset to 0%

### Environment data

Audiobookshelf Server Version: server v2.3.3
Audiobookshelf App Version: 0.9.65-beta

- [ ] Android App?
- [x] iOS App?

#### iOS Issue
iOS Version: 16.5.1

iPhone model: iPhone 14 Pro

### Notes

I saw similar issues about progress loss, but didn't see any that fit this exact scenario, so apologies if I missed it.

This has been happening both when closing/reopening the app as well as when I have been listening while disconnected to the server and then reconnect (examples of both below). I see Listening Sessions on my server, so it does appear that listening data is being sent/received. This behavior does not happen when streaming a book, only when playing a downloaded one.

I took a break from audiobooks for a little while (last listen on 7/7/23) and just started back last week. Prior to the break, I hadn't experienced this issue, but it's been consistent ever since I started back. I'm not sure if I was on app version 0.9.65-beta before (looks like it had been released at that point), but it looks like there have been several server releases since then (I have auto-updates turned on and am currently on the latest version).

### Examples

In this video I have been listening to the book while connected to the server. When I exit the app and reopen it, progress has been reset to 0%.

https://github.com/advplyr/audiobookshelf-app/assets/7266957/223a7d75-8b75-4b77-8ffa-2c3cfab3d691

In this video I have been listening to the book locally (on cell network so not connected to my server). When I connect to Wifi and select "Connect to server" within the app (without closing/reopening it), the progress is reset to 0%.

https://github.com/advplyr/audiobookshelf-app/assets/7266957/2b5c18a2-827c-46a5-8afc-e4b1a8330c59

**Comment by jakoss** [comment]
I had this few times for big audio files and re-upload of the same content in chunks seems to help, but no idea why

**Comment by florianehmke** [comment]
I am facing the same issue, also both ways (connected, local). iOS App on 14 pro.

**Comment by noja11** [comment]
I am also experiencing this issue.

**Comment by barelylit** [comment]
Same thing happened to me:

![image](https://github.com/advplyr/audiobookshelf-app/assets/101836977/81f1586c-2d32-4692-a56a-2767f06d9138)

**Comment by barelylit** [comment]
Same thing again this morning

![Screenshot_20230904-093130](https://github.com/advplyr/audiobookshelf-app/assets/101836977/8a40c999-93c4-4882-8e9e-f6e71f56fc03)

**Comment by jakoss** [comment]
I have constant reproduction pattern. Play, hide app to the background, play it for 1 hour. Then pause the playback using external media controller (like bluetooth buds or car music system). Then, if you try to play, the playback is rolledback by the hour. It's like the app saved the position before going into background and then rolling back to it on playback start

**Comment by barelylit** [comment]
That is consistent with what i just experienced, i just paused it with earphone button there

**Comment by advplyr** [comment]
I just reproduced and fixed the issue mentioned by @jakoss

**Comment by advplyr** [comment]
Fixed in [v0.9.66-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.66-beta)

**Comment by sparevermicelli** [comment]
Hi,
I am already using 0.9.79-beta (server 2.18.1), but still facing the same issue.
Was disconnected from the server for a long time (travel), and after I connected back to the server, the progress has been lost.

**Comment by oucil** [comment]
@advplyr I'm on Android using 0.10.0-beta, and on server 2.26.3 and it's doing exactly the same thing. My downloaded audiobooks are starting in random places or losing all progress altogether when switching from home (where the server is located) to car or back. This doesn't seem to be fixed. I don't see another open ticket for this which is why I'm commenting here in the hopes you can open the ticket back up.

**Comment by nichwall** [comment]
> This doesn't seem to be fixed. I don't see another open ticket for this which is why I'm commenting here in the hopes you can open the ticket back up.


This was fixed at the time the issue was closed and marked as completed.

There are a number of sync related issues open, do any of those apply? (see https://github.com/advplyr/audiobookshelf-app/issues?q=is%3Aopen%20is%3Aissue%20label%3A%22progress%20sync%22)
