### ISSUE TITLE
some m4b file not playing in app but working in browser

### ISSUE THREAD

**Issue by Gokalex** [advplyr/audiobookshelf-app#865]
It only happens with some m4b files, not all, should i upload one that doesn't work?
In the app, when i play stream nothing happens, same with download, in the browser (from the same android phone) it streams correctly and downloads the zip.

Audiobookshelf Version:

- [x] Android App

#### Android Issue
Android version: 0.9.65-beta

Device model:
Nothing Phone 1

**Comment by advplyr** [comment]
Please share the full ffprobe you can get from the web client

**Comment by Gokalex** [comment]
{
  "programs": [],
  "streams": [
    {
      "index": 0,
      "codec_name": "aac",
      "codec_long_name": "AAC (Advanced Audio Coding)",
      "profile": "LC",
      "codec_type": "audio",
      "codec_tag_string": "mp4a",
      "codec_tag": "0x6134706d",
      "sample_fmt": "fltp",
      "sample_rate": "22050",
      "channels": 2,
      "channel_layout": "stereo",
      "bits_per_sample": 0,
      "initial_padding": 0,
      "id": "0x1",
      "r_frame_rate": "0/0",
      "avg_frame_rate": "0/0",
      "time_base": "1/22050",
      "start_pts": 0,
      "start_time": "0.000000",
      "duration_ts": 865487872,
      "duration": "39251.150658",
      "bit_rate": "62794",
      "nb_frames": "845203",
      "extradata_size": 2,
      "disposition": {
        "default": 1,
        "dub": 0,
        "original": 0,
        "comment": 0,
        "lyrics": 0,
        "karaoke": 0,
        "forced": 0,
        "hearing_impaired": 0,
        "visual_impaired": 0,
        "clean_effects": 0,
        "attached_pic": 0,
        "timed_thumbnails": 0,
        "captions": 0,
        "descriptions": 0,
        "metadata": 0,
        "dependent": 0,
        "still_image": 0
      },
      "tags": {
        "language": "und",
        "handler_name": "SoundHandler",
        "vendor_id": "[0][0][0][0]"
      }
    },
    {
      "index": 1,
      "codec_name": "bin_data",
      "codec_long_name": "binary data",
      "codec_type": "data",
      "codec_tag_string": "text",
      "codec_tag": "0x74786574",
      "id": "0x2",
      "r_frame_rate": "0/0",
      "avg_frame_rate": "0/0",
      "time_base": "1/1000",
      "start_pts": 0,
      "start_time": "0.000000",
      "duration_ts": 32171850,
      "duration": "32171.850000",
      "nb_frames": "7",
      "extradata_size": 43,
      "disposition": {
        "default": 0,
        "dub": 0,
        "original": 0,
        "comment": 0,
        "lyrics": 0,
        "karaoke": 0,
        "forced": 0,
        "hearing_impaired": 0,
        "visual_impaired": 0,
        "clean_effects": 0,
        "attached_pic": 0,
        "timed_thumbnails": 0,
        "captions": 0,
        "descriptions": 0,
        "metadata": 0,
        "dependent": 0,
        "still_image": 0
      },
      "tags": {
        "language": "eng",
        "handler_name": "SubtitleHandler"
      }
    },
    {
      "index": 2,
      "codec_name": "mjpeg",
      "codec_long_name": "Motion JPEG",
      "profile": "Baseline",
      "codec_type": "video",
      "codec_tag_string": "[0][0][0][0]",
      "codec_tag": "0x0000",
      "width": 500,
      "height": 500,
      "coded_width": 500,
      "coded_height": 500,
      "closed_captions": 0,
      "film_grain": 0,
      "has_b_frames": 0,
      "sample_aspect_ratio": "1:1",
      "display_aspect_ratio": "1:1",
      "pix_fmt": "yuvj420p",
      "level": -99,
      "color_range": "pc",
      "color_space": "bt470bg",
      "chroma_location": "center",
      "refs": 1,
      "id": "0x0",
      "r_frame_rate": "90000/1",
      "avg_frame_rate": "0/0",
      "time_base": "1/90000",
      "start_pts": 0,
      "start_time": "0.000000",
      "duration_ts": 3532603559,
      "duration": "39251.150656",
      "bits_per_raw_sample": "8",
      "disposition": {
        "default": 0,
        "dub": 0,
        "original": 0,
        "comment": 0,
        "lyrics": 0,
        "karaoke": 0,
        "forced": 0,
        "hearing_impaired": 0,
        "visual_impaired": 0,
        "clean_effects": 0,
        "attached_pic": 1,
        "timed_thumbnails": 0,
        "captions": 0,
        "descriptions": 0,
        "metadata": 0,
        "dependent": 0,
        "still_image": 0
      }
    }
  ],
  "chapters": [
    {
      "id": 0,
      "time_base": "1/1000",
      "start": 0,
      "start_time": "0.000000",
      "end": 5227926,
      "end_time": "5227.926000",
      "tags": {
        "title": "001"
      }
    },
    {
      "id": 1,
      "time_base": "1/1000",
      "start": 5227926,
      "start_time": "5227.926000",
      "end": 9587287,
      "end_time": "9587.287000",
      "tags": {
        "title": "002"
      }
    },
    {
      "id": 2,
      "time_base": "1/1000",
      "start": 9587287,
      "start_time": "9587.287000",
      "end": 13846384,
      "end_time": "13846.384000",
      "tags": {
        "title": "003"
      }
    },
    {
      "id": 3,
      "time_base": "1/1000",
      "start": 13846384,
      "start_time": "13846.384000",
      "end": 20254162,
      "end_time": "20254.162000",
      "tags": {
        "title": "004"
      }
    },
    {
      "id": 4,
      "time_base": "1/1000",
      "start": 20254162,
      "start_time": "20254.162000",
      "end": 25759521,
      "end_time": "25759.521000",
      "tags": {
        "title": "005"
      }
    },
    {
      "id": 5,
      "time_base": "1/1000",
      "start": 25759521,
      "start_time": "25759.521000",
      "end": 32171850,
      "end_time": "32171.850000",
      "tags": {
        "title": "006"
      }
    },
    {
      "id": 6,
      "time_base": "1/10000000",
      "start": 321718500000,
      "start_time": "32171.850000",
      "end": 392511506580,
      "end_time": "39251.150658",
      "tags": {
        "title": "007"
      }
    }
  ],
  "format": {
    "filename": "/audiobooks/ENG/Andrzej Sapkowski/The Witcher Saga/1994 - Blood of Elves (Krew elfów)/Blood of elves (the Witcher 1).m4b",
    "nb_streams": 3,
    "nb_programs": 0,
    "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
    "format_long_name": "QuickTime / MOV",
    "start_time": "0.000000",
    "duration": "39251.150658",
    "size": "311521882",
    "bit_rate": "63493",
    "probe_score": 100,
    "tags": {
      "major_brand": "isom",
      "minor_version": "512",
      "compatible_brands": "isomiso2mp41",
      "artist": "Andrzej Sapkowski",
      "composer": "Peter Kenny",
      "album": "Blood of Elves (Unabridged)",
      "date": "2014",
      "encoder": "inAudible 1.97",
      "comment": "For more than a hundred years humans, dwarves, gnomes and elves lived together in relative peace. But times have changed, the uneasy peace is over and now the races once again fight each other - and themselves: Dwarves are killing their kinsmen, and elve",
      "genre": "Audiobook",
      "description": "For more than a hundred years humans, dwarves, gnomes and elves lived together in relative peace. But times have changed, the uneasy peace is over and now the races once again fight each other - and themselves: Dwarves are killing their kinsmen, and elves are murdering humans and elves, at least those elves who are friendly to humans... Into this tumultuous time is born a child for whom the witchers of the world have been waiting. \nCiri, the granddaughter of Queen Calanthe, the Lioness of Cintra, has strange powers and a stranger destiny, for prophecy names her the Flame, one with the power to change the world - for good, or for evil... Geralt, the witcher of Rivia, has taken Ciri to the relative safety of the Witchers' Settlement, but it soon becomes clear that Ciri isn't like the other witchers. As the political situation grows ever dimmer and the threat of war hangs almost palpably over the land, Geralt searches for someone to train Ciri's unique powers. \nBut someone else has an eye on the young girl, someone who understand exactly what the prophecy means - and exactly what Ciri's power can do. This time Geralt may have met his match. Read by Peter Kenny.",
      "title": "Blood of Elves The Witcher, Book 1 (Unabridged)"
    }
  }
}

**Comment by ahm427** [comment]
I had a similar issue today where the book would not stream in the app, but streamed fine in browser. The book series was in m4b format with epub files. I found that removing the epub file fixed this issue for some reason. This same issue occurred for all six volumes of the series, and the same solution of removing the epub file fixed it.

**Comment by Gokalex** [comment]
Tried that, i removed the epub file, re-scanned, but still does not work, tried also removing the pdf file, nope.

**Comment by Mavarius1989** [comment]
Same problem. M4b file and one epub. Deleting epub fixed it instantly, even without rescan.

**Comment by Mavarius1989** [comment]
It also happens with mp3. When you change the epub ebook to supplementary it works again

**Comment by advplyr** [comment]
Found the issue here and it will be fixed in the next server release. You could use the `edge` docker tag if you want the fix quicker

**Comment by advplyr** [comment]
Fixed in [v2.4.4](https://github.com/advplyr/audiobookshelf/releases/tag/v2.4.4)

**Comment by Gokalex** [comment]
Can confirm, just updated the server to 2.4.4 and now it plays on my android phone!
Thanks!

**Comment by MrInveigler** [comment]
Hi, hate to throw a spanner at things, but wanted to report that I'm still seeing this issue. M4B, no epubs or PDFs in the folder. And the server is definitely on 2.4.4. Deleted cache and data from Android App, and still doesn't work. The annoying thing is that it's not ALL M4B files. But yes, consistently works on browser regardless.

**Comment by nichwall** [comment]
> Hi, hate to throw a spanner at things, but wanted to report that I'm still seeing this issue. M4B, no epubs or PDFs in the folder. And the server is definitely on 2.4.4. Deleted cache and data from Android App, and still doesn't work. The annoying thing is that it's not ALL M4B files. But yes, consistently works on browser regardless.

Could be related to this issue?
https://github.com/advplyr/audiobookshelf/issues/1872

**Comment by MrInveigler** [comment]
> > Hi, hate to throw a spanner at things, but wanted to report that I'm still seeing this issue. M4B, no epubs or PDFs in the folder. And the server is definitely on 2.4.4. Deleted cache and data from Android App, and still doesn't work. The annoying thing is that it's not ALL M4B files. But yes, consistently works on browser regardless.
> 
> Could be related to this issue? [advplyr/audiobookshelf#1872](https://github.com/advplyr/audiobookshelf/issues/1872)

so might need to do some re-encoding? Thank you. I will give it a shot and will report back
