### ISSUE TITLE
[iOS] Bluetooth "Pause" > Unable to start play again

### ISSUE THREAD

**Issue by dmmsta** [advplyr/audiobookshelf-app#910]
### Steps to reproduce

1. Open ABS App
2. Choose book
3. Start playback (listening via _any_ BT device
4. Pause playback via the BT device (headphone "pause" gesture / button)
5. Attempt playback re-start via the BT device

### Expected behaviour
- Playback resumes in same way as if pause/play via the app icon

### Actual behaviour
- ABS app appears to reset or act as if opening for the first time.  Have to open the app, select the book that was being listened to and initiate playback as if first time opening for specific session.
- Seems as if the app is force closed in iOS, but is still open in app switcher

### Environment data

Audiobookshelf Version:

- [ 0.9.66 (23) ] iOS App?

Stock or customized system:

- Stock + InTune MDM (for work)

#### iOS Issue
iOS Version: 

- 17.0.3

iPhone model:

- iPhone 12 (MGJ53B/A

**Comment by dmmsta** [comment]
Further testing shows that the above issue is not limited to BT device interactions.

With/without BT device connected, if paused for +5sec's ABS app. seems to reset and have to restart playback as if not listened yet...

**Comment by nichwall** [comment]
Probably the same as https://github.com/advplyr/audiobookshelf-app/issues/770 and https://github.com/advplyr/audiobookshelf-app/issues/844

**Comment by dmmsta** [comment]
While I haven't tested those specific situations - it reads exactly the same.

Checked the following situation:

1. Start playback (iPhone speaker)
2. Lock phone (playback continues)
3. Pause playback from lock screen
4. Allow screen to sleep
5. Awake screen after 30secs
6. ABS "player" no longer visible from lock screen

Unlock phone, open app switcher, and ABS is visible, with last book showing (in the app switch preview...likely just the last known app screen rather than live)
Select app, and it restarts

**Comment by jpcastberg** [comment]
Have been experiencing the same behavior on iphone 13, iOS 17.0.3 - I ran the above steps with two other apps (plexamp, tidal) and they did not close the way that audiobookshelf does, so it seems to be specific to this app.

**Comment by oswalt0** [comment]
Do you log into the server via local only? I was having the same problem, it seems to be an "offline" issue, until I installed Tailscale and now it only does it on my Android that is not going through Tailscale to the library. If you watch the sync at the top when you first start your book as soon as its done refreshing it seems to press pause and then you have to do press play again. Also if you are not connected to your library via an internet connection it also seems to force close the app when you press pause via a Bluetooth connection. I have been able to consistently reproduce the problem if I go back to my local IP and use offline.

**Comment by jpcastberg** [comment]
A couple interesting things I've found:
1. When I build the app from source in xcode, this issue does not occur
2. Digging around in my iphone console, I found some log lines that could be relevant:
```
default	14:34:00.502036-0700	runningboardd	Suspending assertion 34-9076-530472 (target:[xpcservice<com.apple.WebKit.GPU([app<com.audiobookshelf.app(C40A1E62-0183-4498-B76C-AB27BF016ED4)>:9076])>:9079:9079])
default	14:34:00.502078-0700	runningboardd	Suspending assertion 34-9076-530473 (target:[xpcservice<com.apple.WebKit.Networking([app<com.audiobookshelf.app(C40A1E62-0183-4498-B76C-AB27BF016ED4)>:9076])>:9077:9077])
default	14:34:00.502115-0700	runningboardd	Suspending assertion 34-9076-530471 (target:[xpcservice<com.apple.WebKit.WebContent([app<com.audiobookshelf.app(C40A1E62-0183-4498-B76C-AB27BF016ED4)>:9076])>:9078:9078](WebProcess9078))
// ...
error	14:34:00.504306-0700	runningboardd	<private>
// ...
default	14:34:00.510304-0700	runningboardd	Executing termination request for: <RBSProcessPredicate <RBSProcessIdentifierPredicate| 9076>>
default	14:34:00.510641-0700	runningboardd	Found 1 processes to terminate
default	14:34:00.510711-0700	runningboardd	[app<com.audiobookshelf.app(C40A1E62-0183-4498-B76C-AB27BF016ED4)>:9076] Terminating with context: <RBSTerminateContext| code:0x2182BAD2 explanation:Timed-out waiting for process [app<com.audiobookshelf.app(C40A1E62-0183-4498-B76C-AB27BF016ED4)>:9076] to invalidate assertion with identifier 34-9076-530401 and explanation 'Shared Background Assertion 1 for com.audiobookshelf.app'. Direct this report to owners of that process reportType:None maxTerminationResistance:Interactive>
```

**Comment by aweb-01** [comment]
Also having this issue. I primarily use downloaded local copies of the audiobooks which seems to align with the conversation here so far.

**Comment by advplyr** [comment]
I still haven't dug into this deeply yet but I wasn't able to reproduce this on iOS 16.7.1.

Some users that have reported this issue were able to resolve it with a fresh install. What I would be interested in is:
1. Were you using Abs server on v2.2.24 or below and are now running Abs server v2.3.0 or higher
2. Have you reinstalled the app

**Comment by aweb-01** [comment]
> I still haven't dug into this deeply yet but I wasn't able to reproduce this on iOS 16.7.1.
> 
> Some users that have reported this issue were able to resolve it with a fresh install. What I would be interested in is:
> 
> 1. Were you using Abs server on v2.2.24 or below and are now running Abs server v2.3.0 or higher
> 2. Have you reinstalled the app

I just started using both the app and server about 3 weeks ago, so both are relatively fresh installs. Server version is 2.4.4. 

I did a fresh reinstall of the app this morning and gave it a quick test, it seems to be working okay so far. I’ll respond again in a few days one way or the other to report back.

**Comment by helio4k** [comment]
Unfortunately I have tried to uninstall and reinstall the application but having the same issue as everyone else.

**Comment by oswalt0** [comment]
Mine is right back to doing it again, Server 2.4.4, App iOS 0.9.66, iPhone 13 17.0.3. I have deleted and reinstalled the app with no change.

**Comment by jpcastberg** [comment]
Digging more into the console logs produced by the app, I am seeing this log line (which occurred before the log lines I posted above):
```
error	19:31:55.012128-0700	Audiobookshelf	Background task still not ended after expiration handlers were called: <private>. This app will likely be terminated by the system. Call UIApplication.endBackgroundTask(_:) to avoid this.
```

`endBackgoundTask` marks the end of a task started by `beginBackgroundTask`. `beginBackgroundTask` requests a task assertion from the system (basically a request for extra time to run code when the app is sent to the background. If the time runs out before `endBackgroundTask` is called, then iOS kills the app) - so this log line is probably relevant to the log line that seems to log the termination of the app:

```
default	19:31:59.966542-0700	runningboardd	[app<com.audiobookshelf.app((null))>:17934] Terminating with context: <RBSTerminateContext| code:0x2182BAD2 explanation:Timed-out waiting for process [app<com.audiobookshelf.app((null))>:17934] to invalidate assertion with identifier 17243-17934-67457 and explanation 'Shared Background Assertion 0 for com.audiobookshelf.app'. Direct this report to owners of that process reportType:None maxTerminationResistance:Interactive>
```

See Swift documentation: https://developer.apple.com/documentation/uikit/uiapplication/1623051-beginbackgroundtask

As far as I can see, the ABS app starts background tasks in three places, all within PlayerProgress.swift :https://github.com/advplyr/audiobookshelf-app/blob/6b164bdb276b835df9d0dc14bf43c43910009fa9/ios/App/Shared/player/PlayerProgress.swift

So - if the app is tanking because a background task isn't finishing, the culprit is probably there. Will continue to look but am admittedly a little out of my element here.

**Comment by gh0sti** [comment]
seems like anytime iOS gets an update we have to reinstall the app, that doesn't seem like a good solution going forward.

**Comment by nichwall** [comment]
> seems like anytime iOS gets an update we have to reinstall the app, that doesn't seem like a good solution going forward.

It will not be required long term, the Android app does not need to be reinstalled every update. The recommendation to reinstall is a temporary solution until the iOS app is more stable (iOS lags behind Android for many features and bug fixes since many of the contributors only use Android)

**Comment by philhagger** [comment]
Same issue for me. Reinstalling doesn’t solve.

**Comment by advplyr** [comment]
Users in discord confirmed that this issue is fixed in the iOS release today v0.9.67-beta

**Comment by yur1xpp** [comment]
@advplyr It seems like this issue came back in 0.9.73 (31) ?

**Comment by advplyr** [comment]
Not that I'm aware of?

**Comment by yur1xpp** [comment]
Huh, I'll try to do more testings on this. It seems to be broken for me, as well as not auto starting when connected to car Bluetooth in my car when I already listened it half way through and stopped for gas. (AFAIK I don't have this issue in previous betas)

**Comment by oswalt0** [comment]
It seems to only happen when I'm not connected to the server. If I'm offline every time I pause by Bluetooth it force closes. If I'm connected to the server it stays open no problem.

**Comment by yur1xpp** [comment]
Oh right I forgot to mention that I'm also using it offline. This explains it. Hopefully it is something can be fixed.
