### ISSUE TITLE
[iOS]: Reporting 0 second sessions to server

### ISSUE THREAD

**Issue by alfawei** [advplyr/audiobookshelf-app#970]
### Describe the issue

Docker v2.6.0, iOS SE2022, iOS 16.7.2

Listen from iOS deveice, but the time was not recorded.
You stats always did not sync back to server.
Time Listened always show 0.

![your stats](https://github.com/advplyr/audiobookshelf/assets/39586201/29bf2886-7de8-406e-8775-f77205ecc562)

![your stats-2](https://github.com/advplyr/audiobookshelf/assets/39586201/71b2af56-8ec9-4fab-b7f7-512c74adcbec)

### Steps to reproduce the issue

under wifi or 4G  connection

### Audiobookshelf version

v2.6.0

### How are you running audiobookshelf?

Docker

**Comment by alfawei** [comment]
Today I deleted docker and local podcasts files , docker deployed again on Synology nas. Creat user , same issue again. 
docker version 2.6.0, iOS version 0.9.70-beta.

sometimes I switch the network from Wi-Fi to 5G data connection, close app on iOS.  The data changed on the website when I refreshed the stat page.

**Comment by advplyr** [comment]
I had this happen to me in testing so I'll find a fix for it.

**Comment by advplyr** [comment]
Fixed in [0.9.72-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.72-beta)

**Comment by alfawei** [comment]
> Fixed in [0.9.72-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.72-beta)

still have problem as before in some podcast, even update to 0.9.72-beta

**Comment by advplyr** [comment]
@alfawei Are you using server v2.8.0?
